# Generated by Django 3.2.3 on 2023-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image_url',
            field=models.URLField(default='/temp.jpg'),
        ),
    ]
