# Generated by Django 3.2.3 on 2023-03-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image_url',
        ),
    ]
